package ar.fiuba.CB100;

public enum Direccion {
	ARRIBA, ABAJO, IZQUIERDA, DERECHA, ADELANTE, ATRAS,
	ARRIBA_DERECHA, ARRIBA_IZQUIERDA, ARRIBA_ADELANTE, ARRIBA_ATRAS,
	ABAJO_IZQUIERDA, ABAJO_DERECHA, ABAJO_ADELANTE, ABAJO_ATRAS,
	ARRIBA_IZQUIERDA_ADELANTE, ARRIBA_IZQUIERDA_ATRAS, ARRIBA_DERECHA_ADELANTE, ARRIBA_DERECHA_ATRAS,
	ABAJO_IZQUIERDA_ADELANTE, ABAJO_IZQUIERDA_ATRAS, ABAJO_DERECHA_ADELANTE, ABAJO_DERECHA_ATRAS;
}
